### PR TITLE
pools: Make `PoolWallet` a `dataclass`

### PR DESCRIPTION
**Pull request by xdustinface**
This fixes plotnft state transition failures introduced by #12796 / #13231 when the ploftnft was created from DB on startup like below: 

```
2022-09-12T09:34:41.272 wallet chia.wallet.wallet_node    : ERROR    Error adding states.. 'PoolWallet' object has no attribute '_update_pool_config_after_sync_task' Traceback (most recent call last):
  File "/home/dustinface/chia-blockchain/chia/wallet/wallet_node.py", line 780, in receive_state_from_peer
    await self.wallet_state_manager.new_coin_state(states, peer, fork_height)
  File "/home/dustinface/chia-blockchain/chia/wallet/wallet_state_manager.py", line 1138, in new_coin_state
    success = await wallet.apply_state_transition(cs, curr_coin_state.spent_height)
  File "/home/dustinface/chia-blockchain/chia/pools/pool_wallet.py", line 301, in apply_state_transition
    await self.update_pool_config_after_sync()  # Update pool config after we finish syncing.
  File "/home/dustinface/chia-blockchain/chia/pools/pool_wallet.py", line 310, in update_pool_config_after_sync
    if self._update_pool_config_after_sync_task is None or self._update_pool_config_after_sync_task.done():
AttributeError: 'PoolWallet' object has no attribute '_update_pool_config_after_sync_task'
```

By making `PoolWallet` a `dataclass` with the default assignment for `_update_pool_config_after_sync_task ` https://github.com/Chia-Network/chia-blockchain/blob/07f36255beb28c8d86ced0327ad4a095381514c8/chia/pools/pool_wallet.py#L79

---- 

A less distractive fix/patch would be to copy/paste this line https://github.com/Chia-Network/chia-blockchain/blob/f4023c47be4941181315063e959a11875d46c5ce/chia/pools/pool_wallet.py#L370 into `PoolWallet.create_from_db`. Im fine with retargeting this PR to `main` and opening the single line fix into release if someone wants to complain :)

### CODE REVIEW

**Review by mariano54 — DISMISSED** [review]

**Review by aqk — DISMISSED** [review]
Thanks for pointing out the alternate, smaller fix. Your change is better - we should go with that.

**Comment by altendky** [comment]
Drafted since this isn't for release.  https://github.com/Chia-Network/chia-blockchain/pull/13432 is being considered.

**Comment by xdustinface** [comment]
> Drafted since this isn't for release. #13432 is being considered.

Un-Draft into `main` :)

**Review by jack60612 — DISMISSED** [review]
lgtm

**Comment by jack60612** [comment]
everyone loves dataclasses

**Review by altendky — DISMISSED** [review]

File: chia/pools/pool_wallet.py [hunk 1]
```diff
@@ -1001,4 +1004,4 @@ def puzzle_hash_for_pk(self, pubkey: G1Element) -> bytes32:
 if TYPE_CHECKING:
     from chia.wallet.wallet_protocol import WalletProtocol
 
-    _dummy: WalletProtocol = PoolWallet()
+    _dummy: WalletProtocol = PoolWallet()  # type: ignore[call-arg]  # Ignore missing args for type checks
```
Comment (altendky) [inline chia/pools/pool_wallet.py:1007]: There are other options for this check.  I'll follow up on this soon and adjust them all.  For now this is an easy change.

```suggestion
    _dummy: WalletProtocol = cast(PoolWallet, None)
```

**Review by altendky — APPROVED** [review]

**Review by emlowe — APPROVED** [review]
