### ISSUE TITLE
[BUG] Can't init or run Chia after updating from 1.1.3 to 1.1.4 latest

### ISSUE THREAD

**Issue by boner-cmd** [Chia-Network/chia-blockchain#3860]
Can't `chia init` after update to 1.1.4

1. Pull 1.1.4 latest
2. activate using `. ./activate`
3. try `chia init`

**Expected behavior**
actually run init

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Kubuntu 20.10
- CPU: AMD, 6 core 12 thread

Error is:
> `ImportError: cannot import name 'serialized_length' from 'clvm_rs' (/home/andrew/chia-blockchain/venv/lib/python3.8/site-packages/clvm_rs.cpython-38-x86_64-linux-gnu.so)`

**Comment by boner-cmd** [comment]
I can run the Chia menu, but so far that's all

**Comment by boner-cmd** [comment]
Rolling back to 1.1.3 still has the error, so going to do a whole fresh pull and see if it fixes

**Comment by boner-cmd** [comment]
Wiped the whole thing, it works now, disregard
