### PR TITLE
install-gui.sh on Ubuntu 18.04 

### PR DESCRIPTION
**Pull request by A-Caccese**
Changed `python` to `python3.7` in line 39.

### CODE REVIEW

**Comment by hoffmang9** [comment]
Looking at the change - this won't work on any machine that has python 3.8 or 3.9 installed. What's the actual issue you're trying to get at?

**Comment by hoffmang9** [comment]
Also, if you have successfully completed install.sh - this script needs to be and assumes you are in the venv. That means that calling 'python' is going to call it from the venv which will be whatever version install.sh settled on - python3.7, 3.8, and soon 3.9.

**Comment by A-Caccese** [comment]
> 
> 
> Looking at the change - this won't work on any machine that has python 3.8 or 3.9 installed. What's the actual issue you're trying to get at?

Before changing the Python version in the install-gui script, I was getting an error while installing node on Ubuntu 18.04.

**Comment by hoffmang9** [comment]
Had you run `. ./activate` before running `sh install-gui.sh`?

**Comment by A-Caccese** [comment]
> 
> 
> Had you run `. ./activate` before running `sh install-gui.sh`?

Sure, I activated the virtual environment before installing the gui.

**Comment by hoffmang9** [comment]
I just tried this again on a completely fresh Ubuntu 18.04 LTS.

If I run outside the venv
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'run'
```

But everything works fine from inside the venv. That particular call `python -c 'import subprocess; process = subprocess.run(["lsb_release", "-rs"], stdout=subprocess.PIPE); print(float(process.stdout) < float(20.04))'` returns True when in the venv and the error above when not.

What was your exact error?

**Comment by A-Caccese** [comment]
> 
> 
> I just tried this again on a completely fresh Ubuntu 18.04 LTS.
> 
> If I run outside the venv
> 
> ```
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> AttributeError: 'module' object has no attribute 'run'
> ```
> 
> But everything works fine from inside the venv. That particular call `python -c 'import subprocess; process = subprocess.run(["lsb_release", "-rs"], stdout=subprocess.PIPE); print(float(process.stdout) < float(20.04))'` returns True when in the venv and the error above when not.
> 
> What was your exact error?

```
npm ERR! Linux 5.3.0-46-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mr-ac/Chia-Network/chia-blockchain/electron-react/npm-debug.log
```

**Comment by A-Caccese** [comment]
Ok, I've checked one more time and the problem appears to be shell related. Sorry for the waste of time.

**Comment by Mortadella-project** [comment]
how did you solve the problem it gives me the same error. can you help me?
