### ISSUE TITLE
[Bug] TypeError: ConsensusConstants.__new__() missing 3 required positional arguments: 'SOFT_FORK2_HEIGHT', 'SOFT_FORK4_HEIGHT', and 'HARD_FORK_FIX_HEIGHT'

### ISSUE THREAD

**Issue by PatrickTulskie** [Chia-Network/chia-blockchain#18736]
### What happened?

When upgrading from 2.4.3 to 2.4.4 on the release branch, and then calling `chia init`, chia refuses to boot. Reverting back to 2.4.3 clears the issue.

### Version

2.4.4

### What platform are you using?

Pi4

### What ui mode are you using?

CLI

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/jivemastert/chia-blockchain/venv/bin/chia", line 3, in <module>
    from chia.cmds.chia import main
  File "/home/jivemastert/chia-blockchain/chia/cmds/chia.py", line 9, in <module>
    from chia.cmds.beta import beta_cmd
  File "/home/jivemastert/chia-blockchain/chia/cmds/beta.py", line 10, in <module>
    from chia.cmds.beta_funcs import (
  File "/home/jivemastert/chia-blockchain/chia/cmds/beta_funcs.py", line 8, in <module>
    from chia.cmds.cmds_util import format_bytes, prompt_yes_no, validate_directory_writable
  File "/home/jivemastert/chia-blockchain/chia/cmds/cmds_util.py", line 14, in <module>
    from chia.consensus.default_constants import DEFAULT_CONSTANTS
  File "/home/jivemastert/chia-blockchain/chia/consensus/default_constants.py", line 13, in <module>
    DEFAULT_CONSTANTS = ConsensusConstants(
                        ^^^^^^^^^^^^^^^^^^^
TypeError: ConsensusConstants.__new__() missing 3 required positional arguments: 'SOFT_FORK2_HEIGHT', 'SOFT_FORK4_HEIGHT', and 'HARD_FORK_FIX_HEIGHT'
```

**Comment by BrandtH22** [comment]
Hey @PatrickTulskie , as a heads up we can generally provide more timely and thorough support in our discord server (https://discord.gg/chia).

If you are installing from source are you removing the `venv`, `penv`, and `.venv` files prior to running the install script?

i.e. while in the chia-blockchain directory running these commands:
```
rm -r venv
rm -r .penv
rm -r .venv
```

Prior to running the git and install commands:
```
git fetch
git checkout latest
git reset --hard FETCH_HEAD --recurse-submodules
git status
sh install.sh
```

These instructions were taken from the upgrade section here:
https://docs.chia.net/installation/#from-source

**Comment by PatrickTulskie** [comment]
Got it. That worked. My previous upgrade script came from instructions were from the GitHub wiki version of the docs, not the new ones which didn't have the virtual env cleanup part.

In any case, I'll close this out since it looks like this isn't an actual bug. Thanks for the assistance.
