### PR TITLE
Add `change_data` to `_state_changed` since the later calls expect it

### PR DESCRIPTION
**Pull request by cmmarslender**
Fixes
```
2022-07-13T16:00:16.167 full_node chia.seeder.crawler     : ERROR    Exception: state_changed() missing 1 required positional argument: 'change_data'. Traceback: Traceback (most recent call last):
  File "/home/ubuntu/chia-blockchain/chia/seeder/crawler.py", line 166, in crawl
    self._state_changed("loaded_initial_peers")
  File "/home/ubuntu/chia-blockchain/chia/seeder/crawler.py", line 331, in _state_changed
    self.state_changed_callback(change)
TypeError: state_changed() missing 1 required positional argument: 'change_data'
```

Was broken by https://github.com/Chia-Network/chia-blockchain/commit/04c822b2c367af77e2cfe24bfc97f739f575e664 with the addition of specific args without defaults for the `change_data` param

### CODE REVIEW

File: chia/rpc/rpc_server.py [hunk 1]
```diff
@@ -85,7 +85,7 @@ async def _state_changed(self, change: str, change_data: Optional[Dict[str, Any]
                 tb = traceback.format_exc()
                 log.warning(f"Sending data failed. Exception {tb}.")
 
-    def state_changed(self, change: str, change_data: Dict[str, Any]) -> None:
+    def state_changed(self, change: str, change_data: Dict[str, Any] = None) -> None:
```
[the remark this answers is not in the document]
Comment (cmmarslender) [reply chia/rpc/rpc_server.py]: Yep saw the linter yelling. just pushed that fix.

**Review by altendky — APPROVED** [review]
Reads ok to me and fixes an error.  I would like @xdustinface to look it over either before or after merge though.

**Review by emlowe — APPROVED** [review]

**Review by xdustinface — APPROVED** [review]
