### PR TITLE
Set the type correctly (SortKey) for click 

### LINKED ISSUE #13640: [Bug] 'chia wallet get_transactions' isn't working in git-main
### What happened?

````
$ chia wallet get_transactions
Exception from 'wallet' 'str' object has no attribute 'name'
````

### Version

chia-blockchain-1.6.1b4.dev16

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by emlowe**
Make sure to set the type correctly for click - otherwise, click 8 defaults to a string type
Fixes #13640

Other strangeness in the click setup for these options ignored

### CODE REVIEW

**Review by altendky — APPROVED** [review]

**Review by paninaro — APPROVED** [review]
Tested, working.

**Comment by atomsymbol** [comment]
This patch didn't fix issue #13640. Please read https://stackoverflow.com/questions/44446945/python-how-to-get-name-of-the-enum

**Comment by emlowe** [comment]
I believe it does fix it, however, a subsequent PR overwrote the code

**Comment by atomsymbol** [comment]
Ok, so it was caused by a missing type annotation. `get_transactions` works in 1.6.1-rc2. Thanks.
