### PR TITLE
Fix attribute error on `FullNode.simulator_transaction_callback`

### PR DESCRIPTION
**Pull request by altendky**
Introduced in https://github.com/Chia-Network/chia-blockchain/pull/12072/files#diff-a84a0802b416c9c5a5fdc6d2293c4c7971ca0b1519f246ede123e304a56e540a.

```
Jul 17 17:52:45 fullnode chia_full_node[1175517]: 2022-07-17T17:52:45.239 full_node chia.full_node.full_node: ERROR    Error in _handle_one_transaction, closing: Traceback (most recent call last):
Jul 17 17:52:45 fullnode chia_full_node[1175517]:   File "/farm/chia-blockchain/chia/full_node/full_node.py", line 318, in _handle_one_transaction
Jul 17 17:52:45 fullnode chia_full_node[1175517]:     inc_status, err = await self.respond_transaction(entry.transaction, entry.spend_name, peer, entry.test)
Jul 17 17:52:45 fullnode chia_full_node[1175517]:   File "/farm/chia-blockchain/chia/full_node/full_node.py", line 2117, in respond_transaction
Jul 17 17:52:45 fullnode chia_full_node[1175517]:     if self.simulator_transaction_callback is not None:  # callback
Jul 17 17:52:45 fullnode chia_full_node[1175517]: AttributeError: 'FullNode' object has no attribute 'simulator_transaction_callback'
```

I'm not sure the `FullNode` should reference the simulator at all, but in so much as it does it should define all the used attributes in `.__init__()`.

### CODE REVIEW

**Review by jack60612 — DISMISSED** [review]
LGTM, did not realize it was not a dataclass.

**Review by jack60612 — APPROVED** [review]
lgtm

**Review by wjblanke — APPROVED** [review]
aok
