### ISSUE TITLE
BladeBit just hangs when running from GUI[Bug] 

### ISSUE THREAD

**Issue by Drhicom** [Chia-Network/chia-blockchain#12972]
### What happened?

Good morning, Simple question, does BladeBit work in the GUI of 1.5.0 and is there anything else that needs to be installed besides chia-1.5.0. I have DELL t7610 DUAL CPU e5-2670 AND 512gb of Ram. When I looked at the log this is what it puts out. System Memory: 497/511 GiB.
Memory require
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000015E24B2B040>
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000015E24AF5550>
transport: <ProactorSocketTransport fd=-1 read=>
Traceback (most recent call last):
File "asyncio\sslproto.py", line 690, in processwrite_backlog
File "asyncio\proactor_events.py", line 359, in write
File "asyncio\proactor_events.py", line 395, in loopwriting
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function SSLProtocolTransport.del_ at 0x0000015E23500940>
Traceback (most recent call last):
File "asyncio\sslproto.py", line 321, in del
File "asyncio\sslproto.py", line 316, in close
File "asyncio\sslproto.py", line 599, in startshutdown
File "asyncio\sslproto.py", line 604, in writeappdata
File "asyncio\sslproto.py", line 712, in processwrite_backlog
File "asyncio\sslproto.py", line 726, in fatalerror
File "asyncio\proactor_events.py", line 151, in forceclose
File "asyncio\base_events.py", line 751, in call_soon
File "asyncio\base_events.py", line 515, in checkclosed
RuntimeError: Event loop is closed
Seeing that ssl error I shut down chia and reran the C:\Users\rb653504\AppData\Local\chia-blockchain\app-1.5.0\resources\app.asar.unpacked\daemon> .\chia.exe init -c c:\files\ca\ to recreate the SSL certs just in case no change.

### Version

1.5.0

### What platform are you using?

Windows 10 Enterprise

### What ui mode are you using?

GUI

### Relevant log output

```shell
System Memory: 497/511 GiB.
Memory require
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000015E24B2B040>
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000015E24AF5550>
transport: <ProactorSocketTransport fd=-1 read=>
Traceback (most recent call last):
File "asyncio\sslproto.py", line 690, in processwrite_backlog
File "asyncio\proactor_events.py", line 359, in write
File "asyncio\proactor_events.py", line 395, in loopwriting
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function SSLProtocolTransport.del_ at 0x0000015E23500940>
Traceback (most recent call last):
File "asyncio\sslproto.py", line 321, in del
File "asyncio\sslproto.py", line 316, in close
File "asyncio\sslproto.py", line 599, in startshutdown
File "asyncio\sslproto.py", line 604, in writeappdata
File "asyncio\sslproto.py", line 712, in processwrite_backlog
File "asyncio\sslproto.py", line 726, in fatalerror
File "asyncio\proactor_events.py", line 151, in forceclose
File "asyncio\base_events.py", line 751, in call_soon
File "asyncio\base_events.py", line 515, in checkclosed
RuntimeError: Event loop is closed
Seeing that ssl error I shut down chia and reran the C:\Users\rb653504\AppData\Local\chia-blockchain\app-1.5.0\resources\app.asar.unpacked\daemon> .\chia.exe init -c c:\files\ca\ to recreate the SSL certs just in case no change.
```

**Comment by ZzDaniel** [comment]
Same problem.

**Comment by harold-b** [comment]
Let's take this back to https://github.com/Chia-Network/bladebit/issues/201 as it seems the root cause is OOM issue on windows.

There might be some work to do on the gui side if it hangs indefinitely, but I'll follow that up on the side with the relevant engineers.

**Comment by Drhicom** [comment]
Please let us know what you would like us to do and test.

**Comment by paninaro** [comment]
@harold-b assigned to you for now, but feel free to bounce it back if there's something on the GUI side that you discover.
