### ISSUE TITLE
[Bug] [v2.0.0-RC4] Cannot run the GUI wallet due to "ModuleNotFoundError"

### ISSUE THREAD

**Issue by Ealrann** [Chia-Network/chia-blockchain#15934]
### What happened?

Hello,

I'm used to install chia from source, on Archlinux, and I wanted to give a try to the v2.0.0 RC2. (wallet only)
The CLI appears to work so far.

When I launch the GUI wallet, it remains stuck on "Loading keyring status", and I get some error in the console (see bellow).
Here the commands I used to build:

```
git checkout -- .
git checkout 2.0.0-rc2
git reset --hard --recurse-submodules
git status    # shows no modifications, HEAD is now at 40134512c remove chip13 (#15871)
sh install.sh
. ./activate
chia init
cd chia-blockchain-gui
git fetch
cd ..
chmod +x ./install-gui.sh
./install-gui.sh
bash start-gui.sh &
```

No error during the build/install

### Version

v2.0.0-RC2

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
# bash ~/git/chia-blockchain/start-gui.sh &
[1] 13216
### Checking GUI dependencies
Found npm 9.8.1
### Checking GUI build
Found /home/ealrann/git/chia-blockchain/chia-blockchain-gui/packages/gui/build/electron/main.js
### Starting GUI
npm run electron

> root@2.0.0-rc3.dev0 electron
> npm run start:gui

> root@2.0.0-rc3.dev0 start:gui
> lerna run start --scope @chia-network/gui

lerna notice cli v7.1.3
lerna notice filter including "@chia-network/gui"
lerna info filter [ '@chia-network/gui' ]

> @chia-network/gui:start

> @chia-network/gui@2.0.0-rc3.dev0 start
> npm run electron
> @chia-network/gui@2.0.0-rc3.dev0 electron
> electron .
Checking if userData migration is needed
/home/ealrann/.config/Chia Blockchain/Local Storage/leveldb exists: true
/home/ealrann/.chia/mainnet/gui/Chia Blockchain/Local Storage/leveldb exists: true
/home/ealrann/.config/Chia Blockchain/Local Storage/leveldb/migrated exists: true
Migration needed: false
Setting user data directory to /home/ealrann/.chia/mainnet/gui/Chia Blockchain
Running python script
Script ../../../chia/daemon/server.py
child process success
stderr: Traceback (most recent call last):
  File "/home/ealrann/git/chia-blockchain/chia-blockchain-gui/packages/gui/../../../chia/daemon/server.py", line 25, in <module>
    from chia.cmds.init_funcs import check_keys, chia_full_version_str, chia_init
stderr:   File "/home/ealrann/git/chia-blockchain/chia/cmds/init_funcs.py", line 13, in <module>
    from chia.consensus.coinbase import create_puzzlehash_for_pk
  File "/home/ealrann/git/chia-blockchain/chia/consensus/coinbase.py", line 8, in <module>
    from chia.wallet.puzzles.p2_delegated_puzzle_or_hidden_puzzle import puzzle_hash_for_pk
  File "/home/ealrann/git/chia-blockchain/chia/wallet/puzzles/p2_delegated_puzzle_or_hidden_puzzle.py", line 66, in <module>
    from chia.types.blockchain_format.program import Program
  File "/home/ealrann/git/chia-blockchain/chia/types/blockchain_format/program.py", line 6, in <module>
    from chia_rs import ALLOW_BACKREFS, run_chia_program, tree_hash
ImportError: cannot import name 'ALLOW_BACKREFS' from 'chia_rs' (/home/ealrann/.local/lib/python3.11/site-packages/chia_rs/__init__.py)
closing code: 1
```

**Comment by bramv-chia** [comment]
Please delete your `venv` and retry the `install.sh` for Chia again.

**Comment by Ealrann** [comment]
I just removed everything, and build again, same problem.

I just tried with the v2.0.0.RC4, and it's still stuck at "Loading keyring status", but it's due to a new error : 
`stderr: ModuleNotFoundError: No module named 'blspy'`

Everything works fine on 1.8.2

To build, I deleted my repo, and started from scratch: 
```
rm -rf chia-blockchain/
git clone https://github.com/Chia-Network/chia-blockchain.git -b 2.0.0-rc4 --recurse-submodules
cd chia-blockchain/
git log 
# on commit : * 630846b66 - (HEAD, tag: 2.0.0-rc4) Bump chia-blockchain-gui to 2.0.0-rc4 (#15989) (Jeff 2 days ago)

sh install.sh

. ./activate
chia init
chmod +x ./install-gui.sh
./install-gui.sh

bash start-gui.sh &
```

The complete log :

```
### Checking GUI dependencies
(venv) ealrann ~/git/chia-blockchain [(no branch) !]
└─ 16:44 # Found npm 9.8.1
### Checking GUI build
Found /home/ealrann/git/chia-blockchain/chia-blockchain-gui/packages/gui/build/electron/main.js
### Starting GUI
npm run electron

> root@2.0.0-rc5.dev0 electron
> npm run start:gui


> root@2.0.0-rc5.dev0 start:gui
> lerna run start --scope @chia-network/gui

lerna notice cli v7.1.3
lerna notice filter including "@chia-network/gui"
lerna info filter [ '@chia-network/gui' ]

> @chia-network/gui:start

> @chia-network/gui@2.0.0-rc5.dev0 start
> npm run electron
> @chia-network/gui@2.0.0-rc5.dev0 electron
> electron .
Checking if userData migration is needed
/home/ealrann/.config/Chia Blockchain/Local Storage/leveldb exists: true
/home/ealrann/.chia/mainnet/gui/Chia Blockchain/Local Storage/leveldb exists: true
/home/ealrann/.config/Chia Blockchain/Local Storage/leveldb/migrated exists: true
Migration needed: false
Setting user data directory to /home/ealrann/.chia/mainnet/gui/Chia Blockchain
Running python script
Script ../../../chia/daemon/server.py
child process success
stderr: Traceback (most recent call last):
  File "/home/ealrann/git/chia-blockchain/chia-blockchain-gui/packages/gui/../../../chia/daemon/server.py", line 21, in <module>
    from blspy import G1Element
stderr: ModuleNotFoundError: No module named 'blspy'
closing code: 1
```

**Comment by bramv-chia** [comment]
As an alternative could you use the .deb installer from the `https://chia.net/downloads` page ?

**Comment by Ealrann** [comment]
Deb is not native to Archlinux, but I guess I could do some tricks to use it. 
But still, why are the GUI dependencies not resolved properly on this new version ? I build from source since the v1.0, and it always worked

**Comment by wallentx** [comment]
> . ./activate

I'm running Arch (btw), and I haven't seen any issue like this. After you activate your venv, can you do a `pip list` and share the output?

**Comment by Ealrann** [comment]
Arch FTW! 
Here the `pip list`:
```
Package                Version       Editable project location
---------------------- ------------- ---------------------------------
aiofiles               23.1.0
aiohttp                3.8.4
aiosignal              1.3.1
aiosqlite              0.19.0
anyio                  3.7.0
async-timeout          4.0.3
attrs                  23.1.0
bitstring              4.0.2
blspy                  2.0.2
boto3                  1.26.161
botocore               1.29.165
cffi                   1.15.1
charset-normalizer     3.2.0
chia-blockchain        2.0.0rc7.dev0 /home/ealrann/git/chia-blockchain
chia_rs                0.2.10
chiabip158             1.2
chiapos                2.0.2
chiavdf                1.0.10
click                  8.1.3
clvm                   0.9.7
clvm-tools             0.4.6
clvm_tools_rs          0.1.34
colorama               0.4.6
colorlog               6.7.0
concurrent-log-handler 0.9.24
cryptography           41.0.1
dnslib                 0.9.23
dnspython              2.3.0
filelock               3.12.2
frozenlist             1.4.0
idna                   3.4
importlib-metadata     6.8.0
jaraco.classes         3.3.0
jeepney                0.8.0
jmespath               1.0.1
keyring                23.13.1
miniupnpc              2.2.2
more-itertools         10.1.0
multidict              6.0.4
packaging              23.1
pip                    23.2.1
portalocker            2.7.0
psutil                 5.9.4
pycparser              2.21
python-dateutil        2.8.2
PyYAML                 6.0
s3transfer             0.6.1
SecretStorage          3.3.3
setproctitle           1.3.2
setuptools             65.5.0
six                    1.16.0
sniffio                1.3.0
sortedcontainers       2.4.0
typing_extensions      4.6.3
urllib3                1.26.16
watchdog               2.2.0
wheel                  0.41.1
yarl                   1.9.2
zipp                   3.16.2
zstd                   1.5.5.1
```

**Comment by wallentx** [comment]
Can you try to start the gui by:
```
cd chia-blockchain
git fetch --all
git checkout release/2.0.0
[[ -z $VIRTUAL_ENV ]] || deactivate
[[ -d "venv" ]] && rm -rf venv
./install.sh &> /tmp/install.log
. ./activate
CI=true ./install-gui.sh &> /tmp/install-gui.log
cd chia-blockchain-gui
npm run electron 2>&1 | tee /tmp/start-gui.log
```

If your GUI still fails in the same way, could you provide the 3 log files produced in `/tmp/` from the above commands?

![2023-08-23_13-59](https://github.com/Chia-Network/chia-blockchain/assets/8990544/b742b213-9167-423f-b45c-8fbdab5b0f39)

**Comment by wallentx** [comment]
> Deb is not native to Archlinux, but I guess I could do some tricks to use it. But still, why are the GUI dependencies not resolved properly on this new version? I build from source since the v1.0, and it always worked
> 
> I just tried with RC6, same error.

If you do want to try the .deb route, [debtap](https://aur.archlinux.org/packages/debtap) from the AUR works well.

**Comment by Ealrann** [comment]
Thanks for your time!

Ok, I deleted again my repo (`rm -rf ~/git/chia-blockchain/`), 
and I used these commands to rebuild:
```
git clone https://github.com/Chia-Network/chia-blockchain.git --recurse-submodules
cd chia-blockchain
git checkout release/2.0.0
git log # => 8c83d938d - (HEAD -> release/2.0.0, tag: 2.0.0-rc6, origin/release/2.0.0) 
           #      Bump chia-blockchain-gui to 2.0.0-rc6 (#16105) (Jeff 6 days ago)
[[ -z $VIRTUAL_ENV ]] || deactivate
[[ -d "venv" ]] && rm -rf venv
./install.sh &> /tmp/install.log
. ./activate
CI=true ./install-gui.sh &> /tmp/install-gui.log
cd chia-blockchain-gui
npm run electron 2>&1 | tee /tmp/start-gui.log
```

Unfortunately, the 
`CI=true ./install-gui.sh &> /tmp/install-gui.log` did nothing (returned instantly), and the start-gui returned an error:
![image](https://github.com/Chia-Network/chia-blockchain/assets/723000/d3f68ff6-ae1a-4b29-b837-55ea26f0c1ce)

[install.log](https://github.com/Chia-Network/chia-blockchain/files/12422658/install.log)
[install-gui.log](https://github.com/Chia-Network/chia-blockchain/files/12422659/install-gui.log)
[start-gui.log](https://github.com/Chia-Network/chia-blockchain/files/12422660/start-gui.log)


I'm available on discord if you want/need to debug that faster  (Ealrann#5116)

**Comment by Ealrann** [comment]
The install-gui.sh finished without error. I then run 
```
CI=true ./install-gui.sh &> /tmp/install-gui.log
cd chia-blockchain-gui
npm run electron 2>&1 | tee /tmp/start-gui.log
```
Here the result:
![image](https://github.com/Chia-Network/chia-blockchain/assets/723000/7fce5163-63af-424d-a4aa-e748444f3cd8)



[install.log](https://github.com/Chia-Network/chia-blockchain/files/12422876/install.log)
[install-gui.log](https://github.com/Chia-Network/chia-blockchain/files/12422877/install-gui.log)
[start-gui.log](https://github.com/Chia-Network/chia-blockchain/files/12422878/start-gui.log)

**Comment by wallentx** [comment]
I pinged you on discord.
What if after you've activated your venv, but before you try to `npm run electron`, you just `pip install --force blspy`, and then try to `npm run electron`?

**Comment by paninaro** [comment]
I would focus your efforts on getting the daemon to run, and ignore trying to run the GUI until that is confirmed to be working properly. I suspect that you'll see the same `blspy` issue if you just run `chia run_daemon` from the CLI.

**Comment by Ealrann** [comment]
> I pinged you on discord. What if after you've activated your venv, but before you try to `npm run electron`, you just `pip install --force blspy`, and then try to `npm run electron`?

No it didn't solve the issue, I attach the log. 

----

I updated to 2.0.0 (branch latest), same problem 😭


[log.log](https://github.com/Chia-Network/chia-blockchain/files/12432229/log.log)
![Screenshot from 2023-08-24 20-05-04](https://github.com/Chia-Network/chia-blockchain/assets/723000/84548527-e883-499f-b581-7021c324933f)

**Comment by paninaro** [comment]
Sure, running the daemon alone won't start any other services. I was just curious if you would see the same blspy issue when running the daemon alone.

By the way, you can always start chia services _before_ starting the GUI. I frequently will run `chia start farmer` and then launch the GUI. I expect that would at least get you past initial failure you're seeing.

**Comment by arvidn** [comment]
> ImportError: cannot import name 'ALLOW_BACKREFS' from 'chia_rs' (/home/ealrann/.local/lib/python3.11/site-packages/chia_rs/__init__.py)

That error happens when you install the wrong version of `chia_rs`. The right version is the one specified in `setup.py`. Sometimes you have to `pip uninstall chia_rs` before running `sh install.sh` to get the right version. I don't think our `install.sh` script may necessarily *replace* a wheel with the right version. So, wiping the venv and starting from scratch is typically the safest bet.

**Comment by arvidn** [comment]
> Note: I updated to v2.0.0 (branch latest), same problem 😭

I would not expect the state of your *repository* to affect this problem. I believe it's entirely caused by the python environment. Either your venv or your system python packages interfering with the venv.

One interesting experiment would be to, in a terminal where the `venv` is activated, run `python` and at the prompt type:
```
>>> import blspy
>>> blspy.__file__
```

If the first line also fails with not finding the library, make sure your venv has installed it. Does `pip install blspy` return an error? (when the venv is active).

If you successfuly import `blspy` the second line will print where it was loaded from. it should point into your `venv` directory. If it doesn't, it suggests you have another `blspy` installed somewhere that overrides the venv.

**Comment by zhando** [comment]
Hello. Having the same problem.. Same "blspy" message.  I also use Arch Linux. Someone in discord speculated I was running a "Chia Network Gui". If he meant I was connecting the UI to a remote daemon, yes, I did experiment with that at one time and decided it wasn't for me. I backed it out. Maybe I didn't do a good job. I'm looking into it. Anyway he suggest I install blspy. Ok I did that from pacman, i.e. pacman -S python-blspy. Didn't help but the error did change:

> > @chia-network/gui:start

> @chia-network/gui@2.0.1 start
> npm run electron
> @chia-network/gui@2.0.1 electron
> electron .
> Checking if userData migration is needed
> /home/summa/.config/Chia Blockchain/Local Storage/leveldb exists: true
> /home/summa/.chia/mainnet/gui/Chia Blockchain/Local Storage/leveldb exists: true
> /home/summa/.config/Chia Blockchain/Local Storage/leveldb/migrated exists: true
> Migration needed: false
> Setting user data directory to /home/summa/.chia/mainnet/gui/Chia Blockchain
> Running python script
> Script ../../../chia/daemon/server.py
> child process success
> stderr: Traceback (most recent call last):
>   File "/home/summa/chia-blockchain/chia-blockchain-gui/packages/gui/../../../chia/daemon/server.py", line 24, in <module>
>     from chia import __version__
> ModuleNotFoundError: No module named 'chia'
> closing code: 1
> libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

**Comment by Ealrann** [comment]
> Sometimes you have to `pip uninstall chia_rs` before running `sh install.sh` to get the right version. I don't think our `install.sh` script may necessarily _replace_ a wheel with the right version. So, wiping the venv and starting from scratch is typically the safest bet.

Uninstalling chia_rs didn't solve it unfortunately (at least, the GUI doesn't works, same error)

```
>>> import blspy
>>> blspy.__file__
'/home/ealrann/git/chia-blockchain/venv/lib/python3.11/site-packages/blspy.cpython-311-x86_64-linux-gnu.so'
```

It looks fine. But maybe the GUI doesn't use this package for some reasons?

**Comment by paninaro** [comment]
The GUI doesn't use any python packages because it's an Electron app (Node.js/TypeScript/React). What the GUI _is_ doing is launching the daemon, which is a python process. That's where the blspy import issue is coming from.

It might be interesting to see if the daemon is able to run if we extract just the bit of code that launches the daemon from the GUI. Here's a CLI that will do that:

`node -e "const childProcess = require('child_process'); const Process = childProcess.spawn; const script = '../../../chia/daemon/server.py'; const processOptions = {}; let pyProc = new Process('python', [script, '--wait-for-unlock'], processOptions);"`

Also, the output from @zhando is a bit different since it's complaining about importing `chia` instead of `blspy`. That might be completely unrelated and would seem to point to a bad build or improper venv setup.

Another thing to try would be to modify `chia/daemon/server.py` to reorder the imports, and see if delaying the import of blspy reveals other issues. As an example, I would try changing server.py:

![image](https://github.com/Chia-Network/chia-blockchain/assets/339312/4803b44c-4413-447a-8af6-92ff86d371a8)

**Comment by Ealrann** [comment]
Unfortunately, the command `node -e "const childProcess = require('child_process'); const Process = childProcess.spawn; const script = '../../../chia/daemon/server.py'; const processOptions = {}; let pyProc = new Process('python', [script, '--wait-for-unlock'], processOptions);"`
appears to do nothing (at least, no output)

-----

When I move the import `from blspy import G1Element` lower, the GUI still stay stuck, but the error is different : 
```
Running python script
Script ../../../chia/daemon/server.py
child process success
stderr: Traceback (most recent call last):
  File "/home/ealrann/git/chia-blockchain/chia-blockchain-gui/packages/gui/../../../chia/daemon/server.py", line 23, in <module>
    from chia import __version__
ModuleNotFoundError: No module named 'chia'
```

**Comment by zhando** [comment]
@paninaro 

"The output from @zhando is a bit different since it's complaining about importing chia instead of blspy."

My original complaint was about blspy, but I made it go away by installing blspy at the system level of Arch Linux, i.e. yay -S python-blspy.. That's when the gui complained about missing module chia.

Something in the gui startup is wrecking the venv.. If you start up chia services with like "chia start farmer", the gui seems to have no startup issues.

**Comment by paninaro** [comment]
My suspicion is that launching from Electron/node is mucking with the environment, but it's odd that this is only being seen with Arch installations.

Here's another change to try. Instead of having the GUI launch `../../../chia/daemon/server.py`, we can try having it run the `../../../venv/bin/chia_daemon` script:

The changes below are in the `chia-blockchain-gui/packages/gui/src/util/chiaEnvironment.js` file. We're redefining the constants that specify the daemon process to launch (from `server.py` to `chia_daemon`). Note the change in the `getScriptPath()` function which normally appends `.py`, but for this test we want to remove that part.

![image](https://github.com/Chia-Network/chia-blockchain/assets/339312/1fb4facf-e24b-45fc-88a1-d38dd867c64b)

**Comment by Ealrann** [comment]
I made the change, and rebuilt the gui (maybe it wasn't necessary?)
Same behavior : 
```
stderr: Traceback (most recent call last):
  File "/home/ealrann/git/chia-blockchain/chia-blockchain-gui/packages/gui/../../../venv/bin/chia_daemon", line 5, in <module>
    from chia.daemon.server import main
ModuleNotFoundError: No module named 'chia'
```

**Comment by paninaro** [comment]
Can you verify that you're running node 16.20.1? For 2.0.0 we were using 16.20.1. We've updated to 18 (18.16.1) in chia-blockchain-gui main, but you may not be using that.

`node --version`

**Comment by zhando** [comment]
> Can you verify that you're running node 16.20.1? For 2.0.0 we were using 16.20.1. We've updated to 18 (18.16.1) in chia-blockchain-gui main, but you may not be using that.
> 
> `node --version`

v20.5.1 for me.

**Comment by zhando** [comment]
I made the changes to the .js file as well.. No change for me. Can't find chia module.

I removed python-blspy (system level module) and the blspy message is back.. If you could install "chia" at the system level, it seems you could get past that but that of course is dumb.

**Comment by zhando** [comment]
Also, if you start up chia services first with say, 'chia start farmer', not only does the gui fire up with no apparent problem (save for prompting for the passphrase but the cli took care of that), but you still see the same error messages; missing blspy or missing chia (yeah I reinstalled blspy at system level to see).

**Comment by zhando** [comment]
wallentx found a workaround and a path to solution. See the support in the discord.

**Comment by BrandtH22** [comment]
wallentx's workaround:

lerna is the culprit
in the short term, if you activate your venv, and cd to `chia-blockchain-gui/packages/gui`, and run `../../node_modules/.bin/electron .` it should work
you have to be in that exact dir, and run that exact command to execute electron

from: https://discord.com/channels/1034523881404370984/1034870571864948777/1149781177624952965

**Comment by Ealrann** [comment]
this works for me too, yeay!

**Comment by zhando** [comment]
Ok I noticed this on the 2.1.0 rc's as well. Arch Linux..

Fire up the GUI and it appears ok at first.. Type in a couple of characters of the passphrase and the screen whites out.

None of the workarounds help anymore. Attached is a video.

https://github.com/Chia-Network/chia-blockchain/assets/91598/e69eb9d7-668f-447b-81fe-d97d7351a70c

**Comment by BrandtH22** [comment]
> Ok I noticed this on the 2.1.0 rc's as well. Arch Linux..
> 
> Fire up the GUI and it appears ok at first.. Type in a couple of characters of the passphrase and the screen whites out.
> 
> None of the workarounds help anymore. Attached is a video.
> box-231005-1418-38.mp4

Thank you for the info, it does however appear that the video became corrupt. Would you be able to re-upload that?

**Comment by zhando** [comment]
> > Ok I noticed this on the 2.1.0 rc's as well. Arch Linux..
> > Fire up the GUI and it appears ok at first.. Type in a couple of characters of the passphrase and the screen whites out.
> > None of the workarounds help anymore. Attached is a video.
> > box-231005-1418-38.mp4
> 
> Thank you for the info, it does however appear that the video became corrupt. Would you be able to re-upload that?

Plays for me just fine here in the browser frame. Anyone else?

**Comment by paninaro** [comment]
@zhando If you run `chia start farmer` (or whatever), provide your passphrase, and then launch the GUI, does it work or fail somewhere else?

**Comment by Ealrann** [comment]
Same behavior here, the GUI seems to launch correctly, then when typing the passphrase, it comes back to a similar white screen. 

No error before I close the app, then : 
```
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94495)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/home/eal/git/chia-blockchain/chia-blockchain-gui/packages/gui/build/electron/main.js:2:3786688)
    at BrowserWindow.emit (node:events:525:35)
```

I use it in wallet-only, no farmer.

**Comment by zhando** [comment]
> @zhando If you run `chia start farmer` (or whatever), provide your passphrase, and then launch the GUI, does it work or fail somewhere else?

Oh my. That used to work on previous releases.. Now that doesn't work anymore..

https://github.com/Chia-Network/chia-blockchain/assets/91598/e04c031b-e340-4c31-a639-aba529463000

**Comment by paninaro** [comment]
Looks like it's a timing issue, and not related to any input events. I don't have any immediate ideas... white screen issues are tricky to track down due to the lack of logging.

**Comment by Ealrann** [comment]
I think this issue doesn't appear anymore on 2.1.0, so we can close it. The white screens issues seems to be this one now : 
https://github.com/Chia-Network/chia-blockchain/issues/16538
